# Generated by Django 5.0.6 on 2024-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Ваше имя', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Введите Ваш E-mail', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Введите Ваш номер телефона', max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(help_text='Введите Ваш адрес', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
