# Generated by Django 5.0.6 on 2024-07-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Введите номер версии', max_length=10, verbose_name='Номер версии')),
                ('version_name', models.CharField(help_text='Введите название версии', max_length=100, verbose_name='Название версии')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('product', models.ForeignKey(help_text='Введите версию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='Versions', to='catalog.product')),
            ],
        ),
    ]
