# Generated by Django 5.0.6 on 2024-07-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productversion',
            options={'verbose_name': 'Версия продукта', 'verbose_name_plural': 'Версии продукта'},
        ),
    ]
