# Generated by Django 5.0.6 on 2024-07-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productversion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(help_text='Введите версию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product'),
        ),
    ]
